http_port 3128

acl allowed dstdomain .chatgpt.com
acl allowed dstdomain .ab.chatgpt.com
acl allowed dstdomain .opencode.ai
acl allowed dstdomain .openrouter.ai
acl allowed dstdomain .integrate.api.nvidia.com
acl allowed dstdomain .models.dev
acl allowed dstdomain .oauth2.googleapis.com
acl allowed dstdomain .cloudcode-pa.googleapis.com
acl allowed dstdomain .play.googleapis.com
acl allowed dstdomain .anthropic.com
acl allowed dstdomain .claude.com
acl allowed dstdomain .generativelanguage.googleapis.com
acl allowed dstdomain .openai.com

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed
http_access deny all

cache deny all
